[package]
name = "mac"
version = "0.1.0"
authors = ["Junha Park <tunatone.0111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"
users = "0.11.0"
libc = "0.2.91"