[package]
name = "signtool"
version = "0.1.0"
authors = ["Junha Park <tunatone.0111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
elf = "0.0.10"
openssl = "0.10.34"
